export const transactions = [
  {
    id: 1,
    amount: 100,
    date: "2023-10-24",
    clientName: "John Doe",
    paymentMethod: "Credit Card",
    transactionStatus: "Completed",
  },
  {
    id: 2,
    amount: 200,
    date: "2023-10-25",
    clientName: "Jane Doe",
    paymentMethod: "PayPal",
    transactionStatus: "Pending",
  },
  {
    id: 3,
    amount: 300,
    date: "2023-10-26",
    clientName: "Peter Parker",
    paymentMethod: "Debit Card",
    transactionStatus: "Canceled",
  },
  {
    id: 4,
    amount: 400,
    date: "2023-10-27",
    clientName: "Mary Jane Watson",
    paymentMethod: "Apple Pay",
    transactionStatus: "Completed",
  },
  {
    id: 5,
    amount: 500,
    date: "2023-10-28",
    clientName: "Bruce Wayne",
    paymentMethod: "Bitcoin",
    transactionStatus: "Pending",
  },
  {
    id: 6,
    amount: 600,
    date: "2023-10-29",
    clientName: "Clark Kent",
    paymentMethod: "Cash",
    transactionStatus: "Completed",
  },
  {
    id: 7,
    amount: 700,
    date: "2023-10-30",
    clientName: "Diana Prince",
    paymentMethod: "Check",
    transactionStatus: "Pending",
  },
  {
    id: 8,
    amount: 800,
    date: "2023-10-31",
    clientName: "Arthur Curry",
    paymentMethod: "Bank Transfer",
    transactionStatus: "Completed",
  },
  {
    id: 9,
    amount: 900,
    date: "2023-11-01",
    clientName: "Barry Allen",
    paymentMethod: "Gift Card",
    transactionStatus: "Pending",
  },
  {
    id: 10,
    amount: 1000,
    date: "2023-11-02",
    clientName: "Victor Stone",
    paymentMethod: "Money Order",
    transactionStatus: "Completed",
  },
];
